# Generated by Django 3.0.8 on 2020-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('college', models.CharField(max_length=256)),
                ('degree', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('passout', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=256)),
            ],
        ),
    ]
